### ISSUE TITLE
Links in main navigation mistakenly point to other gh pages

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/absaoss.github.io#2]
Links in main navigation mistakenly point to other GH pages. They should point to short abstract and then provide a link to the main GH pages.

**Comment by ytsarev** [comment]
@Zejnilovic looks like after the merge of #11 we got an undesired effect. 

https://absaoss.github.io/k8gb automatically redirects to https://www.k8gb.io due to GH pages configuration.

**Comment by Zejnilovic** [comment]
@ytsarev a reason more for me to hurry up and fix this issue 👍

**Comment by ytsarev** [comment]
#12 should fix it for k8gb

**Comment by ytsarev** [comment]
okay, I managed to screw it up :) please see #13
